### PR TITLE
Add FancySpacerSymbol to ThemeSettings for user customization

### PR DESCRIPTION
**Pull request by zhaocai**

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
I like the idea of adding these to the settings. However, there are more than those two and they need to be renamed in order to understand what they are :-)

My suggestion is to do the full rename of the hardcoded symbols and rework the settings so people can easily find and adjust what they are looking for.

```
$global:ThemeSettings = New-Object -TypeName PSObject -Property @{
CurrentThemeLocation             = "$PSScriptRoot\Themes\Agnoster.psm1"
MyThemesLocation                 = '~\Documents\WindowsPowerShell\PoshThemes'
ErrorCount                       = 0
GitSymbols                       = @{
    GitBranchSymbol                  = [char]::ConvertFromUtf32(0xE0A0)
    BeforeStashSymbol                = '{'
    AfterStashSymbol                 = '}'
    DelimSymbol                      = '|'
    LocalWorkingStatusSymbol         = '!'
    LocalStagedStatusSymbol          = '~'
    LocalDefaultStatusSymbol         = ''
    BranchUntrackedSymbol            = [char]::ConvertFromUtf32(0x2262)
    BranchIdenticalStatusToSymbol    = [char]::ConvertFromUtf32(0x2263)
    BranchAheadStatusSymbol          = [char]::ConvertFromUtf32(0x2191)
    BranchBehindStatusSymbol         = [char]::ConvertFromUtf32(0x2193)
}
PromptSymbols                    = @{
    FailedCommandSymbol              = [char]::ConvertFromUtf32(0x2A2F)
    TruncatedFolderSymbol            = '..'
    ElevatedSymbol                   = [char]::ConvertFromUtf32(0x26A1)
}
Colors                           = @{
    GitDefaultColor                  = [ConsoleColor]::DarkGreen
    GitLocalChangesColor             = [ConsoleColor]::DarkYellow
    GitNoLocalChangesAndAheadColor   = [ConsoleColor]::DarkMagenta
    PromptForegroundColor            = [ConsoleColor]::White
    PromptHighlightColor             = [ConsoleColor]::DarkBlue
    DriveForegroundColor             = [ConsoleColor]::DarkBlue
    PromptBackgroundColor            = [ConsoleColor]::DarkBlue
    PromptSymbolColor                = [ConsoleColor]::White
    SessionInfoBackgroundColor       = [ConsoleColor]::Magenta
    SessionInfoForegroundColor       = [ConsoleColor]::White
    CommandFailedIconForegroundColor = [ConsoleColor]::DarkRed
    AdminIconForegroundColor         = [ConsoleColor]::DarkYellow
    WithBackgroundColor              = [ConsoleColor]::DarkRed
    WithForegroundColor              = [ConsoleColor]::White
    GitForegroundColor               = [ConsoleColor]::Black
}
}
```

I will list all the symbols and how they should be renamed, give me a few days to get to that (pretty busy ATM). As this will break a lot of people's configs, I want to take this change together with the rename to posh-theme as mentioned in #19.

**Comment by zhaocai** [comment]
Good to Know. I wanted to do this because I stumbled up [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) which include extra symbols: extra symbols for powerline

**Comment by JanDeDobbeleer** [comment]
OH MY GOD! I will do this ASAP!

**Comment by JanDeDobbeleer** [comment]
Ok, so I have a [branch](https://github.com/JanJoris/oh-my-posh/tree/feature/symbols_settings) that enables symbols override. I'm going to test this a bit more and tackle #19 at once too. I just need to find a little bit more time to change that. In the meantime, feel free to checkout that branch :-)

**Comment by zhaocai** [comment]
Thanks for the update. Can you take a look of my comment on the [branch](https://github.com/JanJoris/oh-my-posh/commit/272ddfcefe89f5034bc628107ce350d88340d88c).
1. Use symbol for Powerline start instead of space.
2. Use symbol for drive potion separation instead of '/'

**Comment by JanDeDobbeleer** [comment]
image

Pretty pimp, right?

**Comment by zhaocai** [comment]
Can you also make the leading Powerline start as a customizable symbol instead of ' '? ⚡ Thanks.

**Comment by JanDeDobbeleer** [comment]
Yes, this evening. I'm not doing this fulltime 😎

**Comment by JanDeDobbeleer** [comment]
@zhaocai everything seems to work as expected.

**Comment by zhaocai** [comment]
@JanJoris  It works great.  Thanks for the update.

**Pull request closed without merging**
