### PR TITLE
Update Markdown

### LINKED ISSUE #36: unreadable readme
README is in a non-standard format.

TOC links don't work. 

Goes against markdown [philosophy](http://daringfireball.net/projects/markdown/syntax#philosophy). 

Could you please remove non-standard collapsing HTML elements & use standard headers?

### PR DESCRIPTION
**Pull request by amedee**
Closes #36.

There are 2 remaining issues that I cannot solve myself:

1. There are 3 broken image links
2. The theme preview images are too wide, which makes the text too small to read. Please reduce the width of the images to 888 px. For images with text on the right, this means cutting out a piece in the middle. I could have done it myself but then I would have to store the images in the repository too and that seems a bit of overkill.

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
Damnit. Now I have to install GIMP again 😂. Damn you promo images!

**Comment by JanDeDobbeleer** [comment]
Hate to break your balls, can you rebase and push? I'll change the images this week. No pressure. I wanted to merge @alirobe's PR first as he created the issue.

**Comment by amedee** [comment]
Rebased (well, cherry-picked actually, and then filter-branch to fake the committer date).

**Comment by JanDeDobbeleer** [comment]
Aren't you the little crazy camper 😂

**Comment by alirobe** [comment]
I won't say I told you so. 😉  Thanks for making the effort guys.

**Pull request merged**
